# espanso configuration file
# https://espanso.org/docs/

matches:
  - trigger: "eii"
    replace: "w@waynehoover.com"

  - trigger: "lii"
    replace: "[$|$](https://)"

  - trigger: "pii"
    replace: "424-229-2414"

  - trigger: "aii"
    replace: "265 Bellevue Drive, Boulder, CO 80302"

  - triggers: ["teh", "thee"]
    replace: "the"
    word: true

  - trigger: "<aii"
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"

toggle_key: OFF

